<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\stylelista.razor" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Classes\Contratos\" />
    <Folder Include="Classes\Enumeracoes\" />
    <Folder Include="Classes\Serv\" />
  </ItemGroup>

</Project>
