using static System.Console;
int a, b, c;
Write("Digite o valor de A:");
a = int.Parse(ReadLine());
Write("Digite o valor de B:");
b = int.Parse(ReadLine());
Write("Digite o valor de C:");
c = int.Parse(ReadLine());
bool um = a == c;
bool dois = b != a;
bool tres = b > c;
bool quatro = a <= c;
WriteLine($"O primeiro valor é igual ao terceiro valor? R: {um}");
WriteLine($"O segundo valor é diferente do primeiro valor? R: {dois}");
WriteLine($"O segundo valor é maior que o terceiro valor? R: {tres}");
WriteLine($"O primeiro valor é menor ou igual que o terceiro valor? R: {quatro}");
bool resultado1 = um & tres; 
bool resultado2 = dois | quatro;
bool resultado3 = !um;
WriteLine($"O resultado da pergunta um é: {resultado1}");
WriteLine($"O resultado da pergunta dois é: {resultado2}");
WriteLine($"O resultado da pergunta tres é: {resultado3}");
